<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MedVet.Application\MedVet.Application.csproj" />
      <ProjectReference Include="..\MedVet.Domain\MedVet.Domain.csproj" />
      <ProjectReference Include="..\MedVet.Infrastructre\MedVet.Infrastructre.csproj" />
    </ItemGroup>

</Project>
