// <auto-generated />
using System;
using MedVet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MedVet.Infrastructre.Migrations
{
    [DbContext(typeof(MedVetContext))]
    [Migration("20260415020154_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedVet.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSULTA");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500)");

                    b.Property<Guid>("IdPet")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<Guid>("IdVeterinario")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR2(1000)");

                    b.Property<Guid>("PrescricoesId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("DataConsulta")
                        .HasDatabaseName("IX_CONSULTAS_DATA_CONSULTA");

                    b.HasIndex("IdPet")
                        .HasDatabaseName("IX_CONSULTAS_ID_PET");

                    b.HasIndex("IdVeterinario")
                        .HasDatabaseName("IX_CONSULTAS_ID_VETERINARIO");

                    b.HasIndex("PrescricoesId");

                    b.HasIndex("IdPet", "DataConsulta")
                        .HasDatabaseName("IX_CONSULTAS_PET_DATA");

                    b.ToTable("PJ_CONSULTAS", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Dono", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR2(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_DONOS_EMAIL");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_DONOS_NOME");

                    b.ToTable("PJ_DONOS", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ModoDeUso")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeMedicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMBER(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PJ_MEDICAMENTOS", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)");

                    b.Property<Guid>("IdDono")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_DONO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("TipoAnimal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TIPO_ANIMAL");

                    b.HasKey("Id");

                    b.HasIndex("IdDono")
                        .HasDatabaseName("IX_ANIMAIS_ID_DONO");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_ANIMAIS_NOME");

                    b.HasIndex("Raca")
                        .HasDatabaseName("IX_ANIMAIS_RACA");

                    b.HasIndex("TipoAnimal")
                        .HasDatabaseName("IX_ANIMAIS_TIPO_ANIMAL");

                    b.ToTable("PJ_ANIMAIS", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Prescricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdConsulta")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_CONSULTA");

                    b.HasKey("Id");

                    b.HasIndex("IdConsulta")
                        .IsUnique()
                        .HasDatabaseName("IX_PRESCRICOES_ID_CONSULTA_UNIQUE");

                    b.ToTable("PJ_PRESCRICOES", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Veterinario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Crmv")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CRMV");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200)");

                    b.HasKey("Id");

                    b.HasIndex("Crmv")
                        .IsUnique()
                        .HasDatabaseName("IX_VETERINARIOS_CRMV_UNIQUE");

                    b.HasIndex("Especialidade")
                        .HasDatabaseName("IX_VETERINARIOS_ESPECIALIDADE");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_VETERINARIOS_NOME");

                    b.HasIndex("Nome", "Especialidade")
                        .HasDatabaseName("IX_VETERINARIOS_NOME_ESPECIALIDADE");

                    b.ToTable("PJ_VETERINARIOS", (string)null);
                });

            modelBuilder.Entity("PJ_PRESCRICOES_MEDICAMENTOS", b =>
                {
                    b.Property<Guid>("PrescricaoId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Active")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("IdMedicamento")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdPrescricao")
                        .HasColumnType("RAW(16)");

                    b.HasKey("PrescricaoId", "MedicamentoId");

                    b.HasIndex("IdMedicamento");

                    b.HasIndex("IdPrescricao");

                    b.ToTable("PJ_PRESCRICOES_MEDICAMENTOS", (string)null);
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("MedVet.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("IdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedVet.Domain.Entities.Veterinario", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("IdVeterinario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedVet.Domain.Entities.Prescricao", "Prescricoes")
                        .WithMany()
                        .HasForeignKey("PrescricoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Prescricoes");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Pet", b =>
                {
                    b.HasOne("MedVet.Domain.Entities.Dono", "Dono")
                        .WithMany("Pets")
                        .HasForeignKey("IdDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("PJ_PRESCRICOES_MEDICAMENTOS", b =>
                {
                    b.HasOne("MedVet.Domain.Entities.Medicamento", null)
                        .WithMany()
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedVet.Domain.Entities.Prescricao", null)
                        .WithMany()
                        .HasForeignKey("IdPrescricao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Dono", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("MedVet.Domain.Entities.Veterinario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
